/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32_F103C6.h"
#include "stm32_F103C6_gpio_driver.h"

// Simple delay
void delay(volatile uint32_t time)
{
    for(uint32_t i = 0; i < time; i++);
}

int main(void)
{
    GPIO_PinConfig_t pinConfig;

    // 1. Enable GPIOA clock
    RCC->APB2ENR |= (1 << 2);   // IOPAEN

    // =========================
    // 2. Configure PA0 as OUTPUT (LED)
    // =========================
    pinConfig.GPIO_PinNumber   = GPIO_PIN_0;
    pinConfig.GPIO_PinMode     = GPIO_MODE_OUTPUT_PP;
    pinConfig.GPIO_output_speed = Speed_10MHZ;

    MCAL_GPIO_Init(GPIOA, &pinConfig);

    // =========================
    // 3. Configure PA1 as INPUT (Button)
    // =========================
    pinConfig.GPIO_PinNumber = GPIO_PIN_1;
    pinConfig.GPIO_PinMode   = GPIO_MODE_INPUT_PULL_UP;

    MCAL_GPIO_Init(GPIOA, &pinConfig);

    // =========================
    // 4. Main loop
    // =========================
    while(1)
    {
        // Button pressed? (active LOW)
        if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PinReSet)
        {
            MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PinSet);
        }
        else
        {
            MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_0, GPIO_PinReSet);
        }

        delay(5000);
    }
}
